#!/usr/bin/env python3
"""Materialize the model/ snapshot from the project's own model code.

Single source that (re)generates every file under model/ from the pinned
submodules (third_party/car + third_party/attack-datasources) via the SAME code
the pipeline runs — nothing here re-implements the schema:

    model/car/objects/<object>.yml   one file per CAR object (13): the common
                                     store header + the object's MITRE CAR fields
                                     (descriptions/examples from the CAR model),
                                     plus its superset car_action list.
    model/superset/model-objects.yml       the CAR+ATT&CK object catalogue (~38)
    model/superset/relationship-types.yml  the ATT&CK relationship vocabulary (~243)
    model/superset/relationship-schema.yml the relationship-instance table shape
    model/sql/car.sql                schema-only dump of a fresh CarStore
    model/sql/superset.sql           schema + reference-model seed of a SupersetStore
    model/spindle/identity.yml       the spindle row-identity registry (piiat_mitrecar/
                                     spindle.yml) resolved against the live maps + ids.py
    model/spindle/record.yml         the shape of a spindle — a minted-identity CAR row
    model/spindle/golden.yml         the golden vectors: per entry the key + guid the engine
                                     mints for its sample; the positional and recipe vectors

The sources of truth are the pinned submodules (and, for model/spindle/, the
hand-authored registry piiat_mitrecar/spindle.yml + the maps); a model refresh
is a submodule pin bump — or a registry / map change — after which re-running
this script re-materializes model/ deterministically.

    python model/generate.py
"""
from __future__ import annotations

import glob
import os
import re
import sqlite3
import subprocess
import sys
import tempfile
from contextlib import closing

import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
# Import the project's own model code (works installed or from a bare checkout).
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from piiat_mitrecar import build_data_model, carmodel, spindle, store, superset  # noqa: E402

_CAR_DM = os.path.join(_ROOT, "third_party", "car", "data_model")

# The 13 CAR objects, in the canonical order used everywhere else.
CAR_OBJECTS = [
    "authentication", "driver", "email", "file", "flow", "http", "module",
    "process", "registry", "service", "socket", "thread", "user_session",
]


# --------------------------------------------------------------------------- #
# YAML: block style, source order preserved, no anchors/aliases, deterministic.
# --------------------------------------------------------------------------- #
class _Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):  # never emit &anchors / *aliases
        return True


def _yaml(obj) -> str:
    return yaml.dump(obj, Dumper=_Dumper, sort_keys=False,
                     default_flow_style=False, allow_unicode=True, width=100)


def _write(path: str, header_comment: str, body: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header_comment)
        fh.write(body)


def _submodule_sha(rel_path: str) -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", os.path.join(_ROOT, rel_path), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL)
        return out.decode().strip()
    except Exception:
        return "<unknown — submodule not checked out>"


CAR_SHA = _submodule_sha("third_party/car")
ADS_SHA = _submodule_sha("third_party/attack-datasources")

_PROVENANCE = (f"# Source of truth (pinned submodules):\n"
               f"#   third_party/car @ {CAR_SHA}\n"
               f"#   third_party/attack-datasources @ {ADS_SHA}\n")


def _car_yaml_header(obj: str) -> str:
    return (f"# GENERATED by `python model/generate.py` — do not edit by hand.\n"
            f"# The `{obj}` CAR object: reconstructed from piiat_mitrecar.carmodel /\n"
            f"# store.HEADER (properties) and build_data_model.build_superset (car_action),\n"
            f"# enriched with field descriptions from the pinned car data_model/{obj}.yaml.\n"
            f"{_PROVENANCE}\n")


def _superset_yaml_header(what: str) -> str:
    return (f"# GENERATED by `python model/generate.py` — do not edit by hand.\n"
            f"# {what}\n"
            f"# Reconstructed from piiat_mitrecar.build_data_model / superset.py.\n"
            f"{_PROVENANCE}\n")


# --------------------------------------------------------------------------- #
# Read the raw CAR data_model YAMLs for human descriptions/examples. The field
# LIST + header separation are taken from the project's code (carmodel / store);
# only the prose descriptions come from here (the CAR model is their only source).
# These descriptions/examples are emitted VERBATIM (see model/README.md) and may
# carry upstream typos or imperfect example values; corrections belong upstream.
# --------------------------------------------------------------------------- #
def _load_car_raw() -> dict[str, dict]:
    raw: dict[str, dict] = {}
    for path in sorted(glob.glob(os.path.join(_CAR_DM, "*.yaml"))):
        with open(path, encoding="utf-8") as fh:
            doc = yaml.safe_load(fh)
        key = re.sub(r"[^a-z0-9]+", "_", doc["name"].lower()).strip("_")
        raw[key] = doc
    return raw


def gen_car_objects() -> int:
    raw = _load_car_raw()
    model = carmodel.load()
    sup_model, _ = build_data_model.build_superset()
    sup_actions = {(o["name"][0] if isinstance(o["name"], list) else o["name"]):
                   list(o.get("actions", [])) for o in sup_model["objects"]}

    n = 0
    for obj in CAR_OBJECTS:
        doc = raw.get(obj, {})
        field_desc = {f["name"]: f for f in (doc.get("fields") or [])}

        object_fields = []
        for name in model[obj]["fields"]:
            if name in store.HEADER:  # mirror store._cols: header wins, never dup
                continue
            src = field_desc.get(name, {})
            entry = {"name": name}
            if src.get("description"):
                entry["description"] = str(src["description"]).strip()
            if "example" in src and src["example"] is not None:
                entry["example"] = src["example"]
            object_fields.append(entry)

        out: dict = {"name": obj}
        if doc.get("description"):
            out["description"] = str(doc["description"]).strip()
        # car_action list comes from the superset model_object.actions (CAR
        # actions unioned with any ATT&CK-data-component actions), as the DB seeds it.
        out["car_action"] = sup_actions.get(obj, list(model[obj]["actions"]))
        out["properties"] = {
            # store.HEADER — the common CAR-event header shared by all 13 objects
            # (piiat_mitrecar/store.py). The CAR model does not describe these.
            "common_header": list(store.HEADER),
            # the object's MITRE CAR fields (third_party/car data_model/<obj>.yaml).
            "object_fields": object_fields,
        }
        _write(os.path.join(_HERE, "car", "objects", f"{obj}.yml"),
               _car_yaml_header(obj), _yaml(out))
        n += 1
    return n


def gen_model_objects() -> int:
    sup_model, _ = build_data_model.build_superset()
    objects = []
    for o in sup_model["objects"]:
        name = o["name"][0] if isinstance(o["name"], list) else o["name"]
        objects.append({
            "name": name,
            "source": o.get("source"),
            "actions": list(o.get("actions", [])),
            "definition": o.get("definition"),
        })
    objects.sort(key=lambda d: d["name"])
    _write(os.path.join(_HERE, "superset", "model-objects.yml"),
           _superset_yaml_header(
               "The CAR + ATT&CK data-sources object catalogue (superset model_object):\n"
               "# name / source (car | attack | car+attack) / actions / definition."),
           _yaml({"model_objects": objects}))
    return len(objects)


def gen_relationship_types() -> int:
    _, rels = build_data_model.build_superset()
    grouped: dict[str, list] = {}
    for r in rels:
        grouped.setdefault(r["source"], []).append(
            {"relationship": r["relationship"], "target": r["target"]})
    ordered = {}
    for src in sorted(grouped):
        ordered[src] = sorted(grouped[src],
                              key=lambda d: (d["relationship"], d["target"]))
    _write(os.path.join(_HERE, "superset", "relationship-types.yml"),
           _superset_yaml_header(
               f"The ATT&CK data-source relationship vocabulary ({len(rels)} edge-types),\n"
               "# grouped by source element: source --relationship--> target. This is the\n"
               "# cascade vocabulary; cascade_relationships.yml maps our joins onto it."),
           _yaml({"relationship_types": ordered}))
    return len(rels)


def gen_relationship_schema(sup_db: str) -> None:
    with closing(sqlite3.connect(sup_db)) as con:
        cols = [{"name": row[1], "type": row[2] or "TEXT"}
                for row in con.execute("PRAGMA table_info(relationship)")]
    schema = {"relationship_instance": {
        "table": "relationship",
        "description": ("One row per materialized edge: a source_object "
                        "--relationship--> target_object instance, timestamped and "
                        "pointing back at the car.db rows by guid. See "
                        "piiat_mitrecar/superset.py."),
        "columns": cols,
    }}
    _write(os.path.join(_HERE, "superset", "relationship-schema.yml"),
           _superset_yaml_header(
               "The relationship-instance table shape (superset.db `relationship`),\n"
               "# introspected from piiat_mitrecar.superset.SupersetStore."),
           _yaml(schema))


# --------------------------------------------------------------------------- #
# SQL snapshots — dumped from the SAME store classes the pipeline uses, via
# sqlite3 iterdump(). Body is byte-identical to the model the pins produce.
# --------------------------------------------------------------------------- #
def _sql_body(con: sqlite3.Connection) -> str:
    return "\n".join(con.iterdump())


def _car_sql_header() -> str:
    return (f"-- GENERATED by `python model/generate.py` from piiat_mitrecar.store\n"
            f"-- (a fresh CarStore) via sqlite3 iterdump() — no hand-written SQL.\n"
            f"-- car.sql is SCHEMA-ONLY: the 13 CAR-object tables; no event rows exist\n"
            f"-- without evidence ingestion. Source of truth (pinned submodules):\n"
            f"--   third_party/car @ {CAR_SHA}\n"
            f"--   third_party/attack-datasources @ {ADS_SHA}\n\n")


def _superset_sql_header() -> str:
    return (f"-- GENERATED by `python model/generate.py` from piiat_mitrecar.superset\n"
            f"-- (SupersetStore + seed_model) via sqlite3 iterdump() — no hand-written SQL.\n"
            f"-- Includes the reference model seed (model_object + relationship_type); the\n"
            f"-- relationship instance table is empty (no evidence ingested). Source of truth:\n"
            f"--   third_party/car @ {CAR_SHA}\n"
            f"--   third_party/attack-datasources @ {ADS_SHA}\n\n")


def gen_sql(tmp: str) -> str:
    """Write model/sql/{car,superset}.sql; return the superset.db path (for schema)."""
    car_db = os.path.join(tmp, "car.db")
    store.CarStore(car_db).close()
    with closing(sqlite3.connect(car_db)) as con:
        car_body = _sql_body(con)
    _write(os.path.join(_HERE, "sql", "car.sql"), _car_sql_header(), car_body + "\n")

    sup_db = os.path.join(tmp, "superset.db")
    s = superset.SupersetStore(sup_db)
    s.seed_model()
    s.close()
    with closing(sqlite3.connect(sup_db)) as con:
        sup_body = _sql_body(con)
    _write(os.path.join(_HERE, "sql", "superset.sql"), _superset_sql_header(), sup_body + "\n")
    return sup_db


def gen_spindle() -> int:
    """model/spindle/: the spindle row-identity registry snapshot + the spindle
    record shape — resolved from piiat_mitrecar/spindle.yml, the live maps and
    ids.py by the SAME code the engine mints with (piiat_mitrecar.spindle), so
    the snapshot can never describe an identity the pipeline does not mint."""
    problems = spindle.verify_registry()
    if problems:
        raise SystemExit("spindle registry invalid:\n  - " + "\n  - ".join(problems))
    try:
        # the change protocol's gate: an entry's golden guid moves only with its version
        return len(spindle.write_snapshot(os.path.join(_HERE, "spindle")))
    except ValueError as exc:
        raise SystemExit(f"spindle snapshot not written — {exc}") from None


def main() -> int:
    n_car = gen_car_objects()
    n_obj = gen_model_objects()
    n_rel = gen_relationship_types()
    with tempfile.TemporaryDirectory() as tmp:
        sup_db = gen_sql(tmp)
        gen_relationship_schema(sup_db)
    n_sp = gen_spindle()
    print(f"model/ materialized: {n_car} CAR object files | "
          f"{n_obj} superset model-objects | {n_rel} relationship-types | "
          f"relationship-schema + car.sql + superset.sql | {n_sp} spindle files")
    print(f"pins: car @ {CAR_SHA[:12]} | attack-datasources @ {ADS_SHA[:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
