"""Generate the CAR source (sensor) definitions from the maps (epic #86).

    python -m piiat_mitrecar.gen_sources [--out DIR] [--check]

Writes one ``<source_id>.yaml`` per source into ``--out`` (default: the repo's
``sources/`` directory). Each file is a CAR-schema sensor document EXTENDED with
end-to-end provenance (``derived_from`` / ``extractor`` / ``input_pattern``), all
derived by introspecting :data:`piiat_mitrecar.mappings.MAPPINGS` and the
pipeline routing table — so regenerating keeps the definitions correct after any
map change. Output is deterministic (sorted keys, stable field order), so the
command is idempotent: a clean tree regenerates byte-for-byte.

``--check`` verifies the on-disk files are in sync with the maps (and that the
registry + CAR data model are consistent) WITHOUT writing — for CI. Exit code is
non-zero when anything is out of date or invalid.
"""
from __future__ import annotations

import argparse
import os
import sys

import yaml

from . import sources_model

# the packaged default output location (committed alongside the code)
DEFAULT_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "sources")

_HEADER = ("# GENERATED by `python -m piiat_mitrecar.gen_sources` — do not edit.\n"
           "# Source: piiat_mitrecar.mappings (coverage) + pipeline routing\n"
           "# (extractor/input_pattern). Regenerate after any map change.\n")


def _dump(doc: dict) -> str:
    """A stable, human-readable YAML rendering (keys kept in insertion order)."""
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False,
                          allow_unicode=True, width=100)
    return _HEADER + body


def write_all(out_dir: str) -> list[str]:
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for source_id, doc in sorted(sources_model.all_source_docs().items()):
        path = os.path.join(out_dir, f"{source_id}.yaml")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(_dump(doc))
        written.append(path)
    return written


def check(out_dir: str) -> list[str]:
    """All the ways the generated tree can be wrong; [] means good."""
    problems = sources_model.verify_registry()
    problems += sources_model.validate_against_car_model()
    problems += sources_model.verify_coverage(out_dir)
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="piiat_mitrecar.gen_sources",
                                 description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=DEFAULT_OUT,
                    help="output directory for the source YAMLs (default: ./sources)")
    ap.add_argument("--check", action="store_true",
                    help="verify on-disk sources match the maps; write nothing")
    args = ap.parse_args(argv)
    out_dir = os.path.abspath(args.out)

    reg = sources_model.verify_registry() + sources_model.validate_against_car_model()
    if reg:
        for p in reg:
            print(f"INVALID: {p}", file=sys.stderr)
        return 1

    if args.check:
        problems = sources_model.verify_coverage(out_dir)
        if problems:
            for p in problems:
                print(f"OUT OF DATE: {p}", file=sys.stderr)
            print("run: python -m piiat_mitrecar.gen_sources", file=sys.stderr)
            return 1
        print(f"OK: {len(sources_model.source_ids())} sources in sync ({out_dir})")
        return 0

    written = write_all(out_dir)
    print(f"wrote {len(written)} source definitions to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
