"""CAR *source* (sensor) definitions, generated by introspecting the maps.

MITRE CAR describes each telemetry producer with a **sensor** YAML (see the
`sensors/` directory of mitre-attack/car): what data-model *objects* and
*actions* it observes, and which CAR *fields* it populates for each. Our engine
does not read raw telemetry directly — it normalises the output of a specific
PARSER/TOOL (EvtxECmd, a log2timeline/plaso parser, Zeek, RECmd, JLECmd, …) into
CAR. So *our* sensor is really that derivation method, and its coverage is
exactly what the corresponding map in :mod:`piiat_mitrecar.mappings` emits.

Rather than hand-author (and hand-maintain) a sensor file per source, this module
DERIVES the coverage from the live ``mappings.MAPPINGS`` registry: for each
artefact key it walks every variant's ``object`` / ``action`` / ``props`` /
``native_extract`` and produces a CAR-schema sensor document. Regenerating after
a map change keeps the source definitions correct by construction — see
:mod:`piiat_mitrecar.gen_sources` for the CLI and the round-trip test.

The CAR sensor schema (scripts/sensor_schema.yaml in mitre-attack/car)::

    sensor_name: str()
    sensor_version: any(str(), num())
    sensor_developer: str()
    sensor_url: str()
    sensor_description: str(required=False)
    data_model_coverage: str(required=False)
    analytic_coverage: list(include('analytic'), required=False)
    mappings: list(include('mapping'))
    other_coverage: list(str())
    # mapping: {object: str, action: str, notes: str, fields: list(str)}
"""
from __future__ import annotations

from . import carmodel, mappings

# --- how each artefact key is DERIVED --------------------------------------
# The owner's rule: every source must be traceable to HOW it was produced — the
# parser/tool, not just the artefact. A `Derivation` is that provenance; several
# maps can share one tool (all the plaso_* keys are one parser family each; the
# evtx_* family is EvtxECmd, with the plaso winevt parser as an alternate route).

_EZ = "Eric Zimmerman (EZ Tools)"
_PLASO_DEV = "log2timeline / Plaso project"
_PLASO_URL = "https://github.com/log2timeline/plaso"


class Derivation:
    """Provenance of a source: the raw evidence, the wrapper/extractor that turns
    it into this source's input, and the tool/parser its car.db is built from.

    The owner's end-to-end contract per source is:
        raw evidence  ->  extractor/wrapper  ->  input pattern  ->  map  ->  CAR.
    ``evidence`` / ``tool`` / ``parser`` cover the left three legs; the input
    pattern is derived from the pipeline routing table (see ``_route_patterns``);
    the map coverage is introspected. Nothing here is hand-copied from the maps.
    """

    __slots__ = ("tool", "developer", "url", "parser", "evidence", "alt")

    def __init__(self, tool, developer, url, parser, evidence, alt=None):
        self.tool = tool            # extractor/wrapper name (EvtxECmd, Zeek, …)
        self.developer = developer  # sensor_developer
        self.url = url              # sensor_url (the extractor's home)
        self.parser = parser        # the specific parser/channel/handler invoked
        self.evidence = evidence    # raw evidence type the extractor consumes
        self.alt = alt or []        # alternate derivations (same coverage), as str


def _plaso(parser: str, evidence: str = "disk image / file system",
           alt=None) -> Derivation:
    return Derivation("log2timeline / Plaso", _PLASO_DEV, _PLASO_URL,
                      parser, evidence, alt)


# EvtxECmd is the primary route for the Windows event-log family; the Plaso
# winevt/winevtx parser (via the l2t_winevt adapter) feeds the SAME maps, so it
# is recorded as an alternate derivation on every evtx_* source.
_WINEVT_ALT = "log2timeline / Plaso winevt/winevtx parser (via the l2t_winevt adapter)"


def _evtxecmd(channel: str) -> Derivation:
    return Derivation("EvtxECmd", _EZ, "https://github.com/EricZimmerman/evtx",
                      f"Windows Event Log (.evtx) — {channel}",
                      "raw Windows Event Log (.evtx)", alt=[_WINEVT_ALT])


DERIVATIONS: dict[str, Derivation] = {
    # ---- raw Windows event logs via EvtxECmd (alt: Plaso winevt adapter) -----
    "evtx_security": _evtxecmd("Security channel (4624/4625/4672)"),
    "evtx_security_sessions": _evtxecmd("Security channel (4624/4634/4647/4778/4779)"),
    "evtx_process": _evtxecmd("Security channel (4688)"),
    "evtx_services": _evtxecmd("System 7045 / Security 4697"),
    "evtx_sysmon": _evtxecmd("Microsoft-Windows-Sysmon/Operational"),
    "evtx_bits": _evtxecmd("Microsoft-Windows-Bits-Client/Operational (59/60)"),
    "evtx_rdp": _evtxecmd("TerminalServices channels (21/24/25)"),
    "evtx_more": _evtxecmd("assorted channels (4907/5857/20003/30803/7001/7002/7034)"),
    # ---- log2timeline / Plaso parsers ---------------------------------------
    "l2t_filestat": _plaso("filestat (file-system $STANDARD_INFORMATION times)",
                           "disk image / file system"),
    "l2t_mft": _plaso("mft (NTFS $MFT)", "disk image (NTFS $MFT)"),
    "l2t_usnjrnl": _plaso("usnjrnl (NTFS $UsnJrnl:$J change journal)",
                          "disk image (NTFS $UsnJrnl:$J)"),
    "l2t_lnk": _plaso("lnk (Windows Shortcut)", "disk image (LNK shortcut files)"),
    "l2t_recyclebin": _plaso("recycle_bin / recycle_bin_info2",
                             "disk image ($Recycle.Bin)"),
    "l2t_msiecf": _plaso("msiecf (MS IE Cache File / index.dat)",
                         "disk image (IE index.dat)"),
    "l2t_firefox_cache": _plaso("firefox_cache", "disk image (Firefox cache)"),
    "l2t_firefox_places": _plaso("sqlite/firefox_history (places.sqlite)",
                                 "disk image (Firefox places.sqlite)"),
    "l2t_javaidx": _plaso("java_idx (Java IDX download cache)",
                          "disk image (Java IDX cache)"),
    "l2t_srum": _plaso("esedb/srum (System Resource Usage Monitor)",
                       "disk image (SRUDB.dat ESE database)"),
    "l2t_text": _plaso("syslog (text) — SSH login lines",
                       "disk image (syslog text logs)"),
    "l2t_utmp": _plaso("utmp (Linux login records)",
                       "disk image (utmp login database)"),
    "l2t_utmpx": _plaso("utmpx (macOS/BSD login records)",
                        "disk image (utmpx login database)"),
    "plaso_exec_cron": _plaso("syslog/cron (task-run lines)",
                              "disk image (cron/syslog text logs)"),
    "plaso_exec_prefetch": _plaso("prefetch (Windows Prefetch)",
                                  "disk image (Windows Prefetch)"),
    "plaso_exec_winreg": _plaso("winreg (amcache/userassist/bam/appcompatcache)",
                                "disk image (Windows registry hives)"),
    "plaso_registry": _plaso("winreg (registry key/value plugins)",
                             "disk image (Windows registry hives)"),
    "plaso_shellitem": _plaso("shell items (embedded, e.g. in lnk/registry)",
                              "disk image (embedded shell items)"),
    "plaso_fseventsd": _plaso("fseventsd (macOS FSEvents)",
                              "disk image (macOS fseventsd)"),
    "plaso_olecf": _plaso("olecf (OLE Compound File summary info)",
                          "disk image (OLE compound documents)"),
    "plaso_pecoff": _plaso("pe (PE/COFF metadata)",
                           "disk image (PE/COFF executables)"),
    # ---- Zimmerman EZ tools --------------------------------------------------
    "recmd_batch": Derivation("RECmd", _EZ, "https://github.com/EricZimmerman/RECmd",
                              "Registry (--json batch output)",
                              "disk image (Windows registry hives)"),
    "jlecmd_dest": Derivation("JLECmd", _EZ, "https://github.com/EricZimmerman/JLECmd",
                              "Jump Lists (AutomaticDestinations)",
                              "disk image (Jump List OLE files)"),
    # ---- Zeek ----------------------------------------------------------------
    "zeek_conn": Derivation("Zeek", "The Zeek Project", "https://zeek.org",
                            "conn.log", "network capture (pcap / live traffic)"),
    "zeek_http": Derivation("Zeek", "The Zeek Project", "https://zeek.org",
                            "http.log", "network capture (pcap / live traffic)"),
    "zeek_files": Derivation("Zeek", "The Zeek Project", "https://zeek.org",
                             "files.log", "network capture (pcap / live traffic)"),
    "zeek_smtp": Derivation("Zeek", "The Zeek Project", "https://zeek.org",
                            "smtp.log", "network capture (pcap / live traffic)"),
}

# Sources with no artefact map because the tool already emits finished CAR — the
# pipeline passes them through verbatim (readers.load_piiat_car). Coverage is
# therefore not introspectable from MAPPINGS; recorded here for completeness.
_PASSTHROUGH = {
    "memory": {
        "derivation": Derivation(
            "PIIAT-Mem (Volatility 3)", "Get-Sybers / Volatility Foundation",
            "https://github.com/Get-Sybers/PIIAT-Mem", "memory image (car.db)",
            "memory image"),
        "input_pattern": ["car.db"],
        "description": (
            "PIIAT-Mem normalises a memory image directly into finished MITRE "
            "CAR (its own car.db); the pipeline passes those events through 1:1 "
            "(no re-mapping here). Object/action/field coverage is defined by "
            "PIIAT-Mem, not by this repo's maps, so it is not enumerated here."),
    },
}


# --- coverage introspection -------------------------------------------------

def resolve_actions(action) -> set[str]:
    """Every CAR action a map's ``action`` spec can yield, resolved statically.

    Actions are a literal string or a marker: ``const(v)`` -> {v};
    ``map_value(field, table)`` -> the table's values; ``first(a, b, …)`` ->
    the union of its parts. Any other marker is unresolvable statically and is a
    hard error — a new action-shape must be taught here so coverage stays exact.
    """
    if isinstance(action, str):
        return {action}
    if isinstance(action, tuple):
        kind, arg = action[0], action[1]
        if kind == "const":
            return {arg}
        if kind == "map_value":
            _field, table, _upper = arg
            return {v for v in table.values() if v is not None}
        if kind == "first":
            out: set[str] = set()
            for sub in arg:
                out |= resolve_actions(sub)
            return out
    raise ValueError(f"cannot statically resolve source action: {action!r}")


def _leaves(entry: dict):
    """The concrete maps under an artefact entry: each variant plus a default,
    or the entry itself when it has no variants."""
    if "variants" in entry:
        out = [sub for _pred, sub in entry["variants"] if sub]
        if entry.get("default"):
            out.append(entry["default"])
        return out
    return [entry]


# --- per-field provenance: "this has this / infers this / came from here" ---
# Classify how each CAR property is produced from the source record, so the
# manifest self-documents which values are lifted verbatim vs derived/inferred.
_DERIVE = {"basename", "ext", "lower", "domain_of", "epoch_ts", "concat",
           "exe_path", "host_label", "hex_int", "unescape_backslashes",
           "replace", "at", "ts_before"}
_INFER = {"regex1", "map_value"}


def _base_field(marker):
    """The underlying source record field(s) a marker reads from (or None)."""
    if isinstance(marker, str):
        return marker                          # a bare field name / ts column
    if isinstance(marker, tuple):
        kind, arg = marker[0], marker[1]
        if kind == "const":
            return None
        if kind in ("payload", "userdata"):
            return arg[1]                      # (field, key) -> key
        if kind in ("regex1", "map_value", "replace", "at"):
            return _base_field(arg[0])
        if kind in ("first", "concat", "ts_before"):
            parts = [_base_field(s) for s in arg]
            return " | ".join(p for p in parts if p) or None
        return _base_field(arg)                # single-source transforms
    return None


def classify_field(marker) -> tuple[str, str | None]:
    """(mode, source_field). mode: direct (verbatim), derived (transformed),
    inferred (regex/value-map decision), asserted (constant), coalesced
    (first-available)."""
    if isinstance(marker, str):
        return ("direct", marker)
    if not isinstance(marker, tuple):
        return ("asserted", None)
    kind = marker[0]
    if kind == "const":
        return ("asserted", None)
    if kind in ("payload", "userdata"):
        return ("direct", marker[1][1])
    if kind == "first":
        return ("coalesced", _base_field(marker))
    if kind in _INFER:
        return ("inferred", _base_field(marker))
    if kind in _DERIVE:
        return ("derived", _base_field(marker))
    return ("derived", _base_field(marker))


def field_provenance(artefact_key: str) -> dict[tuple[str, str], dict[str, dict]]:
    """{(object, action): {car_field: {"mode":..., "from":...}}} — how each CAR
    property of this source is produced. Introspected from the map markers."""
    entry = mappings.MAPPINGS[artefact_key]
    out: dict[tuple[str, str], dict[str, dict]] = {}
    for m in _leaves(entry):
        obj = m["object"]
        for field, marker in (m.get("props") or {}).items():
            mode, src = classify_field(marker)
            for action in resolve_actions(m["action"]):
                slot = out.setdefault((obj, action), {})
                # a definite source wins over a null one if variants differ
                if field not in slot or (src and not slot[field].get("from")):
                    slot[field] = {"mode": mode, "from": src}
    return out


def coverage(artefact_key: str) -> dict[tuple[str, str], dict[str, set[str]]]:
    """{(object, action): {"fields": {...CAR fields...},
                            "native": {...join/native fields...}}}
    for one artefact key — the source's full data-model coverage, derived from
    what its map actually emits."""
    entry = mappings.MAPPINGS[artefact_key]
    cov: dict[tuple[str, str], dict[str, set[str]]] = {}
    for m in _leaves(entry):
        obj = m["object"]
        props = set((m.get("props") or {}).keys())
        native = set((m.get("native_extract") or {}).keys())
        for action in resolve_actions(m["action"]):
            slot = cov.setdefault((obj, action), {"fields": set(), "native": set()})
            slot["fields"] |= props
            slot["native"] |= native
    return cov


# --- routing: the extractor OUTPUT -> map link ------------------------------

def _route_patterns() -> dict[str, list[str]]:
    """{artefact key: [filename/suffix patterns it routes on]} from the pipeline
    routing table — the concrete link between a wrapper's OUTPUT file and the map.

    The ``l2t_winevt`` route key is an ADAPTER that fans one Plaso winevt/winevtx
    table out to every evtx_* map, so its patterns are attributed to each of
    them (that is the alternate derivation of the evtx family)."""
    from . import pipeline
    out: dict[str, list[str]] = {}
    for pattern, keys in pipeline.ROUTES:
        expanded: list[str] = []
        for k in keys:
            if k == "l2t_winevt":
                expanded.extend(pipeline.EVTX_MAPS)   # adapter fan-out
            else:
                expanded.append(k)
        for k in expanded:
            out.setdefault(k, [])
            if pattern not in out[k]:
                out[k].append(pattern)
    return out


def input_patterns(artefact_key: str) -> list[str]:
    """The routing pattern(s) whose matching files feed this source (sorted)."""
    return sorted(_route_patterns().get(artefact_key, []))


def _extractor_block(d: Derivation) -> dict:
    """The wrapper/extractor descriptor: tool + how it is invoked + its home."""
    block = {"tool": d.tool, "parser": d.parser, "url": d.url}
    if d.alt:
        block["alternates"] = list(d.alt)
    return block


# --- CAR sensor document ----------------------------------------------------

def _version() -> str:
    try:
        from importlib.metadata import PackageNotFoundError, version
        try:
            return version("piiat-mitrecar")
        except PackageNotFoundError:
            pass
    except Exception:  # noqa: BLE001
        pass
    return "0.1.0"


def build_source_doc(artefact_key: str) -> dict:
    """One artefact key -> a CAR-schema sensor document (a plain dict ready to
    dump as YAML). Deterministic: objects/actions/fields are sorted, so the same
    maps always produce byte-identical output (idempotent generation)."""
    d = DERIVATIONS[artefact_key]
    cov = coverage(artefact_key)

    prov = field_provenance(artefact_key)
    mapping_items = []
    for (obj, action) in sorted(cov):
        slot = cov[(obj, action)]
        note = f"Derived by {d.tool} — {d.parser}."
        # per-field provenance: has this (direct) / infers this (derived|
        # inferred) / came from here (the source field). "field <- source [mode]"
        fp = prov.get((obj, action), {})
        field_prov = {
            f: (f"{fp[f]['from']} [{fp[f]['mode']}]" if fp[f].get("from")
                else f"[{fp[f]['mode']}]")
            for f in sorted(slot["fields"]) if f in fp
        }
        mapping_items.append({
            "object": obj,
            "action": action,
            "notes": note,
            "fields": sorted(slot["fields"]),
            "field_provenance": field_prov,
        })

    objects_covered = sorted({obj for (obj, _a) in cov})
    desc = f"CAR events derived by {d.tool} ({d.parser})."
    if d.alt:
        desc += " Alternate derivation(s): " + "; ".join(d.alt) + "."
    desc += (" Coverage is generated by introspecting this repo's map "
             f"`{artefact_key}` (piiat_mitrecar.mappings); regenerate after any "
             "map change.")

    # native / join keys are NOT CAR data-model fields (they live in the event's
    # `_native`), so they never go in `fields`; recorded in other_coverage so the
    # provenance is still traceable without violating the CAR schema.
    other = []
    for (obj, action) in sorted(cov):
        nat = sorted(cov[(obj, action)]["native"])
        if nat:
            other.append(f"native/join keys ({obj}/{action}): " + ", ".join(nat))

    return {
        "sensor_name": artefact_key,
        "sensor_version": _version(),
        "sensor_developer": d.developer,
        "sensor_url": d.url,
        "sensor_description": desc,
        # --- end-to-end provenance (superset of the CAR sensor schema) --------
        # raw evidence -> extractor/wrapper -> input pattern -> map -> CAR.
        "derived_from": d.evidence,
        "extractor": _extractor_block(d),
        "input_pattern": input_patterns(artefact_key),
        # --- CAR data-model coverage (introspected from the map) --------------
        "data_model_coverage": ", ".join(objects_covered),
        "mappings": mapping_items,
        "other_coverage": other,
    }


def build_passthrough_doc(name: str) -> dict:
    """A CAR sensor doc for a passthrough source (no introspectable map)."""
    spec = _PASSTHROUGH[name]
    d = spec["derivation"]
    return {
        "sensor_name": name,
        "sensor_version": _version(),
        "sensor_developer": d.developer,
        "sensor_url": d.url,
        "sensor_description": spec["description"],
        "derived_from": d.evidence,
        "extractor": _extractor_block(d),
        "input_pattern": list(spec.get("input_pattern", [])),
        "data_model_coverage": "(defined by the producing tool; passthrough)",
        "mappings": [],
        "other_coverage": [f"Derived by {d.tool} — {d.parser} (finished-CAR passthrough)."],
    }


def source_ids() -> list[str]:
    """Every source id a definition is generated for (map-derived + passthrough)."""
    return sorted(list(DERIVATIONS) + list(_PASSTHROUGH))


def all_source_docs() -> dict[str, dict]:
    """{source_id: CAR sensor doc} for every source."""
    docs = {k: build_source_doc(k) for k in DERIVATIONS}
    for name in _PASSTHROUGH:
        docs[name] = build_passthrough_doc(name)
    return docs


# --- reference / verification ----------------------------------------------

def source_id_for(artefact_key: str) -> str:
    """The source id a given map references. A map may declare an explicit
    ``"source"`` key in its entry; otherwise the source id IS the artefact key
    (the sensor_name == the map key, so a map and its source are 1:1 by name)."""
    entry = mappings.MAPPINGS.get(artefact_key, {})
    return entry.get("source", artefact_key)


def load_source(source_id: str, sources_dir: str | None = None) -> dict:
    """Load a generated source YAML from disk (the on-disk contract a map
    references). Falls back to building it in-memory when no directory/file is
    given — so a map can resolve its source without a generation step."""
    if sources_dir is not None:
        import os

        import yaml
        path = os.path.join(sources_dir, f"{source_id}.yaml")
        with open(path, encoding="utf-8") as fh:
            return yaml.safe_load(fh)
    if source_id in _PASSTHROUGH:
        return build_passthrough_doc(source_id)
    return build_source_doc(source_id)


def verify_registry() -> list[str]:
    """Consistency of the source registry against the live maps + routing:
    every map has a derivation, every derivation names a real map, and every
    map-derived source is reachable through the routing table. Returns [] clean.
    """
    problems: list[str] = []
    map_keys = set(mappings.MAPPINGS)
    for key in map_keys - set(DERIVATIONS):
        problems.append(f"map {key!r} has no DERIVATIONS entry (add its provenance)")
    for key in set(DERIVATIONS) - map_keys:
        problems.append(f"DERIVATIONS {key!r} names no live map")
    routed = _route_patterns()
    for key in DERIVATIONS:
        if not routed.get(key):
            problems.append(f"source {key!r} is not reachable from the routing table")
    return problems


def validate_against_car_model() -> list[str]:
    """Every (object, action, field) a source claims must exist in the CAR data
    model. Returns human-readable problems ([] when clean)."""
    model = carmodel.load()
    problems: list[str] = []
    for key in DERIVATIONS:
        for m in build_source_doc(key)["mappings"]:
            obj = m["object"]
            spec = model.get(obj)
            if spec is None:
                problems.append(f"{key}: object {obj!r} not in CAR data model")
                continue
            if m["action"] not in spec["actions"]:
                problems.append(f"{key}: {obj}.{m['action']} not a CAR action")
            for f in m["fields"]:
                if f not in spec["fields"]:
                    problems.append(f"{key}: {obj}.{f} not a CAR field")
    return problems


def verify_coverage(sources_dir: str) -> list[str]:
    """Compare the on-disk generated source files to freshly-introspected
    coverage. Any drift (a map changed but sources weren't regenerated) is
    reported. Returns [] when the directory is in sync."""
    import os
    problems: list[str] = []
    for source_id, fresh in all_source_docs().items():
        path = os.path.join(sources_dir, f"{source_id}.yaml")
        if not os.path.exists(path):
            problems.append(f"{source_id}: missing {path} (run gen_sources)")
            continue
        disk = load_source(source_id, sources_dir)
        # compare the coverage-bearing parts (version/text may legitimately vary)
        if disk.get("mappings") != fresh["mappings"]:
            problems.append(f"{source_id}: mappings drifted from the maps")
        if disk.get("data_model_coverage") != fresh["data_model_coverage"]:
            problems.append(f"{source_id}: data_model_coverage drifted")
    return problems
