"""The spindle row identity as DATA — the registry the engine mints from, its
materialized snapshot, and the guards that hold registry, maps and engine in step.

WHICH fields identify a disk-image row is a RULE, not code (the discipline
relationships.yml sets for the cascade): piiat_mitrecar/spindle.yml declares,
per artefact, the CAR object, the identity-key version and the ordered
identity fields — each a path on the normalized event — plus the positional
fallback. normalize._spindle mints, through the one seam ids.mint,

    guid = uuid5(SPINDLE_NS, canonical_json({"_obj": <car_object>, "_v": <version>,
                                             <name>: <value>, ...}))

(ids.py — the recipe stix.py mints §2.9 ids with). A map references an entry
by name and never spells identity fields itself.

model/spindle/ holds the deterministic snapshot — identity.yml (the registry
resolved against the live maps: variants, actions, versions, the literal
namespaces), record.yml (the shape of a spindle: what a minted-identity row
IS) and golden.yml (the pinned vectors: per entry the key + guid ids.mint
yields for its golden sample, the positional vector, the recipe vector) —
generated by `python model/generate.py` (or this module's CLI) exactly like
the CAR objects are. verify_registry() / verify_golden() / verify_snapshot() /
validate_record() are the drift guards (tests/test_spindle_model.py;
`--check` in CI): verify_golden is the change protocol's gate — an entry's
golden guid and its version must move together.

    python -m piiat_mitrecar.spindle [--out DIR] [--check]
"""
from __future__ import annotations

import argparse
import os
import sys
import uuid

import yaml

from . import ids

_HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY_PATH = os.path.join(_HERE, "spindle.yml")
# the snapshot lives beside the other materialized models
DEFAULT_OUT = os.path.join(_HERE, "..", "model", "spindle")
REGISTRY_FILE, RECORD_FILE, GOLDEN_FILE = "identity.yml", "record.yml", "golden.yml"
FILES = (REGISTRY_FILE, RECORD_FILE, GOLDEN_FILE)
# where a golden sample's values come from: a real corpus row, or a labelled stand-in
GOLDEN_REAL, GOLDEN_SYNTHETIC = "real", "synthetic"
GOLDEN_SOURCES = (GOLDEN_REAL, GOLDEN_SYNTHETIC)
# the recipe vector: canonical_json must sort keys, drop whitespace and keep UTF-8
RECIPE_INPUT = {"b": 1, "a": "é"}

# the scope vocabularies: an ENTRY declares what its identity is designed for,
# a ROW carries what it got (native.spindle_scope)
CROSS_SOURCE, WITHIN_SOURCE, WITHIN_SOURCE_FALLBACK = \
    "cross_source", "within_source", "within_source_fallback"
ENTRY_SCOPES = (CROSS_SOURCE, WITHIN_SOURCE_FALLBACK)
ROW_SCOPES = (CROSS_SOURCE, WITHIN_SOURCE)
# the two native keys a spindle carries
NATIVE_KEY, NATIVE_SCOPE = "spindle_key", "spindle_scope"
_NATIVE = "native."

_rules_cache: dict | None = None


# --------------------------------------------------------------------------- #
# The registry (spindle.yml)
# --------------------------------------------------------------------------- #
def rules() -> dict:
    global _rules_cache
    if _rules_cache is None:
        with open(REGISTRY_PATH, encoding="utf-8") as fh:
            _rules_cache = yaml.safe_load(fh)
    return _rules_cache


def identities() -> dict[str, dict]:
    return rules().get("identities") or {}


def entry(name: str) -> dict:
    """The registry entry a map leaf names — a missing one is a hard error
    (silently minting nothing would drop the row's identity)."""
    e = identities().get(name)
    if e is None:
        raise KeyError(f"no spindle identity {name!r} in spindle.yml")
    return e


def positional() -> list[str]:
    """The positional fallback's fields (raw wrapped-row fields)."""
    return list(rules()["spindle"]["positional"]["fields"])


def positional_version() -> int:
    return int(rules()["spindle"]["positional"]["version"])


def identity_fields(e: dict) -> list[tuple[str, str, str | None]]:
    """An entry's identity as (name, source path, rendering override | None),
    in declared order — a field is `name: <source>` or
    `name: {source: <source>, normalize: <rendering>}`."""
    out = []
    for name, spec in (e.get("identity") or {}).items():
        if isinstance(spec, dict):
            out.append((name, spec.get("source"), spec.get("normalize")))
        else:
            out.append((name, spec, None))
    return out


def golden(e: dict) -> dict:
    """An entry's golden sample: {source: real|synthetic, values: {name: raw value}}
    — the identity values as they stand on the normalized event."""
    g = e.get("golden")
    return g if isinstance(g, dict) else {}


def golden_vector(obj: str, e: dict) -> tuple[str, dict]:
    """(guid, key) ids.mint yields for an entry's golden sample at the entry's
    version — the vector golden.yml pins; a row carrying those values mints
    identically (the engine goes through the same seam)."""
    modes = {n: m for n, _s, m in identity_fields(e) if m is not None}
    return ids.mint(obj, dict(golden(e).get("values") or {}), e["version"], modes)


def positional_vector() -> tuple[str, dict]:
    """(guid, key) for the positional fallback's golden sample."""
    pos = rules()["spindle"]["positional"]
    g = pos.get("golden") or {}
    return ids.mint(g.get("object"), dict(g.get("values") or {}), pos["version"])


# --------------------------------------------------------------------------- #
# The maps that reference it
# --------------------------------------------------------------------------- #
def _leaf_refs():
    """(map key, variant predicate | 'default' | None, leaf) for every concrete map."""
    from . import mappings
    for key in sorted(mappings.MAPPINGS):
        e = mappings.MAPPINGS[key]
        if "variants" not in e:
            yield key, None, e
            continue
        for pred, sub in e["variants"]:
            if sub:
                yield key, pred, sub
        if e.get("default"):
            yield key, "default", e["default"]


def _spindle_name(leaf: dict):
    g = leaf.get("guid")
    return g.get("spindle") if isinstance(g, dict) else None


def _resolvable(source, leaf: dict, model: dict) -> bool:
    """Whether an identity source path names a value THIS leaf emits."""
    if not isinstance(source, str):
        return False
    if source == "timestamp":
        return leaf.get("ts") is not None
    if source == "owning_pid":
        return leaf.get("owning_pid") is not None
    if source.startswith(_NATIVE):
        k = source[len(_NATIVE):]
        return k in (leaf.get("native_extract") or {}) or k in (leaf.get("keep") or [])
    return source in (leaf.get("props") or {}) and source in model[leaf["object"]]["fields"]


def _references() -> dict[str, dict]:
    """{entry name: {maps, variants, actions}} — how the live maps use the registry."""
    from . import sources_model
    refs: dict[str, dict] = {}
    for key, pred, leaf in _leaf_refs():
        name = _spindle_name(leaf)
        if name is None:
            continue
        x = refs.setdefault(name, {"maps": set(), "variants": set(), "actions": set()})
        x["maps"].add(key)
        if pred:
            x["variants"].add(pred)
        x["actions"] |= sources_model.resolve_actions(leaf["action"])
    return refs


def verify_registry() -> list[str]:
    """Registry <-> maps <-> engine consistency; [] means in step:
    the recipe constants the registry documents are the engine's; every
    l2t/Plaso-derived map mints from the registry and no EVTX-family map does
    (Sysmon ProcessGuid / the EVTX record id stay raw); every reference names
    a real entry of the leaf's object, named by the leaf's map key; every
    identity source is a value the leaf emits; every entry is referenced and
    versioned; every rendering is one the engine knows."""
    from . import carmodel, pipeline, sources_model
    problems: list[str] = []
    r = rules()
    spec = r.get("spindle") or {}
    if spec.get("object_key") != ids.OBJECT_KEY:
        problems.append(f"spindle.object_key {spec.get('object_key')!r} != ids.OBJECT_KEY {ids.OBJECT_KEY!r}")
    if spec.get("version_key") != ids.VERSION_KEY:
        problems.append(f"spindle.version_key {spec.get('version_key')!r} != ids.VERSION_KEY {ids.VERSION_KEY!r}")
    ns = spec.get("namespace") or {}
    if ns.get("parent") != "CAR_NS" or uuid.uuid5(ids.CAR_NS, str(ns.get("label"))) != ids.SPINDLE_NS:
        problems.append("spindle.namespace does not reproduce ids.SPINDLE_NS = uuid5(CAR_NS, label)")
    if spec.get("rendering") != ids.RENDER_STR:
        problems.append(f"spindle.rendering must be {ids.RENDER_STR!r} (the global rule the engine applies)")
    if list(spec.get("normalize") or []) != list(ids.RENDERINGS):
        problems.append(f"spindle.normalize must list exactly the engine's renderings {list(ids.RENDERINGS)}")
    pos = (spec.get("positional") or {}) if isinstance(spec.get("positional"), dict) else {}
    fields = pos.get("fields")
    if not isinstance(fields, list) or not fields or not all(isinstance(f, str) and f for f in fields):
        problems.append("spindle.positional.fields must be a non-empty list of wrapped-row field names")
        fields = []
    if not isinstance(pos.get("version"), int) or pos.get("version") < 1:
        problems.append("spindle.positional.version must be an int >= 1")
    if set(spec.get("entry_scopes") or {}) != set(ENTRY_SCOPES):
        problems.append(f"spindle.entry_scopes must be exactly {sorted(ENTRY_SCOPES)}")
    if set(spec.get("row_scopes") or {}) != set(ROW_SCOPES):
        problems.append(f"spindle.row_scopes must be exactly {sorted(ROW_SCOPES)}")

    model = carmodel.load()
    pg = pos.get("golden") if isinstance(pos.get("golden"), dict) else {}
    if pg.get("source") not in GOLDEN_SOURCES:
        problems.append(f"spindle.positional.golden.source must be one of {list(GOLDEN_SOURCES)}")
    if pg.get("object") not in model:
        problems.append("spindle.positional.golden.object must be a CAR object")
    pv = pg.get("values") if isinstance(pg.get("values"), dict) else {}
    if set(pv) != set(fields) or any(v in (None, "") for v in pv.values()):
        problems.append(f"spindle.positional.golden.values must sample exactly the positional fields {fields}")
    idents = identities()
    referenced: set[str] = set()
    for key, pred, leaf in _leaf_refs():
        where = f"{key}" + (f"[{pred}]" if pred else "")
        name = _spindle_name(leaf)
        d = sources_model.DERIVATIONS.get(key)
        plaso = d is not None and d.tool == sources_model.PLASO_TOOL
        if name is None:
            if plaso:
                problems.append(f"{where}: an l2t/Plaso-derived map must mint its guid from the spindle registry")
            continue
        if key in pipeline.EVTX_MAPS:
            problems.append(f"{where}: an EVTX-family map keeps its raw record / Sysmon guid — never a spindle id")
        e = idents.get(name)
        if e is None:
            problems.append(f"{where}: guid names an unregistered spindle identity {name!r}")
            continue
        referenced.add(name)
        if not (name == key or name.startswith(key + "/")):
            problems.append(f"{where}: names {name!r} — an entry is named by its map key (or '<map>/<variant>')")
        if e.get("object") != leaf.get("object"):
            problems.append(f"{where}: entry {name!r} is declared for {e.get('object')!r}, the leaf is {leaf.get('object')!r}")
            continue
        for iname, source, _mode in identity_fields(e):
            if not _resolvable(source, leaf, model):
                problems.append(f"{name}: identity {iname!r} <- {source!r} is not a value {where} emits")

    for name, e in idents.items():
        if not isinstance(e, dict):
            problems.append(f"{name}: entry must be a mapping")
            continue
        if e.get("object") not in model:
            problems.append(f"{name}: object {e.get('object')!r} is not a CAR object")
        if e.get("scope") not in ENTRY_SCOPES:
            problems.append(f"{name}: scope must be one of {list(ENTRY_SCOPES)}")
        if not isinstance(e.get("version"), int) or e.get("version") < 1:
            problems.append(f"{name}: version must be an int >= 1 (the identity-key version hashed as _v)")
        fields_ = identity_fields(e)
        if e.get("scope") == CROSS_SOURCE and not fields_:
            problems.append(f"{name}: a cross_source entry needs at least one identity field")
        if e.get("scope") == WITHIN_SOURCE_FALLBACK and fields_:
            problems.append(f"{name}: a within_source_fallback entry declares no identity fields")
        for iname, source, mode in fields_:
            if iname in ids.RESERVED_KEYS or iname in fields:
                problems.append(f"{name}: identity name {iname!r} is reserved")
            if not isinstance(source, str) or not source:
                problems.append(f"{name}: identity {iname!r} needs a source path")
            if mode is not None and mode not in ids.RENDERINGS:
                problems.append(f"{name}: identity {iname!r} normalize {mode!r} is not one of {list(ids.RENDERINGS)}")
        g = golden(e)
        if g.get("source") not in GOLDEN_SOURCES:
            problems.append(f"{name}: golden.source must be one of {list(GOLDEN_SOURCES)}")
        gv = g.get("values") if isinstance(g.get("values"), dict) else None
        names_ = {f for f, _s, _m in fields_}
        if gv is None:
            problems.append(f"{name}: golden.values must sample every identity name (the pinned vector)")
        elif set(gv) != names_:
            problems.append(f"{name}: golden.values names {sorted(gv)} != the identity names {sorted(names_)}")
        elif any(v in (None, "") for v in gv.values()):
            problems.append(f"{name}: a golden value is blank (a blank component never mints)")
        if name not in referenced:
            problems.append(f"{name}: registry entry referenced by no map")
    return problems


# --------------------------------------------------------------------------- #
# The snapshot (model/spindle/): deterministic, like model/generate.py's
# --------------------------------------------------------------------------- #
def registry_doc() -> dict:
    """identity.yml: the registry resolved against the live maps, in a stable
    order (entries by name; a fixed key order; the identity in declared order)."""
    r = rules()
    spec = r["spindle"]
    refs = _references()
    entries = []
    for name in sorted(identities()):
        e = identities()[name]
        x = refs.get(name) or {"maps": set(), "variants": set(), "actions": set()}
        identity = []
        for iname, source, mode in identity_fields(e):
            item = {"name": iname, "source": source}
            if mode is not None:
                item["normalize"] = mode
            identity.append(item)
        entries.append({
            "name": name,
            "map": name.split("/", 1)[0],
            "variants": sorted(x["variants"]),
            "car_object": e.get("object"),
            "car_action": sorted(x["actions"]),
            "scope": e.get("scope"),
            "version": e.get("version"),
            # the declared (reading) order; canonical JSON sorts the names at mint time
            "identity": identity,
            "fallback": {"scope": WITHIN_SOURCE, "fields": list(spec["positional"]["fields"]),
                         "version": spec["positional"]["version"]},
        })
    return {
        "spindle": {
            "version": spec.get("version"),
            "namespace": {"STIX_NS": str(ids.STIX_NS), "CAR_NS": str(ids.CAR_NS),
                          "SPINDLE_NS": str(ids.SPINDLE_NS)},
            "recipe": {
                "CAR_NS": f'uuid5(NAMESPACE_URL, "{ids.CAR_NS_URL}")',
                "SPINDLE_NS": f'uuid5(CAR_NS, "{spec["namespace"]["label"]}")',
            },
            "mint": (f'uuid5(SPINDLE_NS, canonical_json({{"{ids.OBJECT_KEY}": <car_object>, '
                     f'"{ids.VERSION_KEY}": <version>, <name>: <value>, ...}}))'),
            "seam": "piiat_mitrecar.ids.mint(car_object, identity, version) -> (guid, key); "
                    "ids.guid_of(key) re-mints a row's own native.spindle_key",
            "canonical_json": "sorted keys, no whitespace, UTF-8 (STIX 2.1 §2.9 / RFC 8785)",
            "rendering": spec.get("rendering"),
            "normalize": list(spec.get("normalize") or []),
            "not_hashed": ["source_artefact", "the parser name", "SourceImage / RecordId (unless positional)",
                           "source_host"],
            "object_key": spec.get("object_key"),
            "version_key": spec.get("version_key"),
            "positional": {"fields": list(spec["positional"]["fields"]),
                           "version": spec["positional"]["version"]},
            "entry_scopes": dict(spec.get("entry_scopes") or {}),
            "row_scopes": dict(spec.get("row_scopes") or {}),
        },
        "identities": entries,
    }


def record_doc() -> dict:
    """record.yml: the shape of a spindle — what a minted-identity CAR row IS
    (the model/car/objects convention: name, description, properties)."""
    from . import store
    spec = rules()["spindle"]
    names = sorted({n for e in identities().values() for n, _s, _m in identity_fields(e)})
    pos = list(spec["positional"]["fields"])
    return {
        "name": "spindle",
        "description": ("A spindle is a CAR event row whose guid was MINTED from the record's own "
                        "stable-identity fields (a disk-image row: log2timeline / Plaso and any other "
                        "artefact parser with no sensor-minted id). It is the same table row as any "
                        "other CAR event — the common header plus the object's fields — carrying, in "
                        "native, the readable key its guid was minted from and the scope that "
                        "identity holds for. Sysmon / EVTX rows are not spindles: their guids are "
                        "the sensor's own."),
        "is_a": "CAR event row — model/car/objects/<car_object>.yml (common_header + object_fields); no column is added",
        "minted_by": "piiat_mitrecar.normalize._spindle, from the registry entry (identity.yml) via piiat_mitrecar.ids.mint",
        "properties": {
            "common_header": list(store.HEADER),
            "spindle": [
                {"name": "guid", "column": "guid", "type": "string — RFC 4122 UUID, version 5",
                 "description": (f"uuid5(SPINDLE_NS, canonical_json(native.{NATIVE_KEY})) = "
                                 f"ids.guid_of(native.{NATIVE_KEY}) — re-mintable from the row itself; "
                                 "the key every relationship, dedupe and STIX observation uses")},
                {"name": "car_object", "column": "(the table)", "type": "one of the 13 CAR objects",
                 "description": f"the object the row is; also native.{NATIVE_KEY}.{ids.OBJECT_KEY}"},
                {"name": "car_action", "column": "car_action", "type": "a car_action of the object",
                 "description": ("NOT part of the guid: an entity's events of different actions share "
                                 "it (the dedupe key adds the action)")},
                {"name": "host", "column": "source_host", "type": "string",
                 "description": ("the evidence host the row is scoped to — NOT part of the guid; every "
                                 "consumer scopes by it (the dedupe key, superset edges, derive's "
                                 "observed set, the STIX case ids)")},
                {"name": "timestamp", "column": "timestamp", "type": "ISO-8601 UTC, or null",
                 "description": ("the CAR event time; part of the guid where the entry's identity names "
                                 "it (event_time / last_write / visit_time / run_time / recorded_time); "
                                 "null on an entity record (a PE's compile stamp is not an event)")},
                {"name": "contributing_artefact", "column": "source_artefact", "type": "a map key",
                 "description": ("the artefact map that produced the row = the registry entry's `map` "
                                 "(identity.yml); with car_object and the spindle_key names it resolves "
                                 "the entry the guid was minted under")},
                {"name": "spindle_key", "column": f"native.{NATIVE_KEY}", "type": "object",
                 "shape": {ids.OBJECT_KEY: "car_object", ids.VERSION_KEY: "identity-key version (int)",
                           "<name>": "string"},
                 "names": names, "positional_names": pos,
                 "description": ("the readable identity key the guid was minted from: the object key, "
                                 "the entry's identity-key version, and the entry's identity names "
                                 "(cross_source) or the positional fields (within_source), every "
                                 "value in its rendering (str unless the entry overrides it)")},
                {"name": "spindle_scope", "column": f"native.{NATIVE_SCOPE}", "type": "enum",
                 "values": list(ROW_SCOPES),
                 "description": dict(spec.get("row_scopes") or {})},
                {"name": "container", "column": f"native.{NATIVE_KEY}.{pos[0]} / native.{pos[0]}",
                 "type": "string", "description": ("the raw container the record came from — in the key "
                                                   "of a within_source row; kept natively by the maps "
                                                   "that declare it (the `keep` list)")},
            ],
        },
        "invariants": [
            f"guid == ids.guid_of(native.{NATIVE_KEY}) == uuid5(SPINDLE_NS, canonical_json(native.{NATIVE_KEY}))",
            f"native.{NATIVE_KEY}.{ids.OBJECT_KEY} == car_object",
            f"native.{NATIVE_KEY}.{ids.VERSION_KEY} == the registry entry's version (the positional version on a within_source row)",
            f"native.{NATIVE_SCOPE} == cross_source  <=>  the key's names are the registry entry's identity names",
            f"native.{NATIVE_SCOPE} == within_source <=>  the key's names are the positional fields {pos}",
            "two rows with equal (source_host, car_object, guid, car_action[, target_guid, access_level]) "
            "are one event (relationships.yml dedupe_key)",
            "the guid is invariant under the source, parser and artefact name, the record's position "
            "and the host — only the contributing values and the entry version move it",
        ],
        "validated_by": "piiat_mitrecar.spindle.validate_record (tests/test_spindle_model.py)",
    }


def golden_doc() -> dict:
    """golden.yml: the pinned vectors — for every entry the key and the guid
    ids.mint yields for its golden sample at the entry's version, the
    positional vector, and the recipe vector (canonical_json over a fixed
    input + the three namespaces). The change protocol's evidence: an identity
    change moves an entry's guid, a recipe change moves them all."""
    spec = rules()["spindle"]
    pos = spec["positional"]
    pguid, pkey = positional_vector()
    entries = []
    for name in sorted(identities()):
        e = identities()[name]
        guid, key = golden_vector(e["object"], e)
        entries.append({"name": name, "version": e["version"], "source": golden(e).get("source"),
                        "key": key, "guid": guid})
    return {
        "spindle": {
            "version": spec.get("version"),
            "recipe": {
                "canonical_json": {"input": dict(RECIPE_INPUT), "output": ids.canonical_json(RECIPE_INPUT)},
                "namespaces": {"STIX_NS": str(ids.STIX_NS), "CAR_NS": str(ids.CAR_NS),
                               "SPINDLE_NS": str(ids.SPINDLE_NS)},
                "mint": "guid = uuid5(SPINDLE_NS, canonical_json(key))",
            },
        },
        "positional": {"version": pos["version"], "fields": list(pos["fields"]),
                       "source": (pos.get("golden") or {}).get("source"), "key": pkey, "guid": pguid},
        "identities": entries,
    }


_HEADER = ("# GENERATED by `python model/generate.py` (or `python -m piiat_mitrecar.spindle`) — "
           "do not edit by hand.\n"
           "# {what}\n"
           "# Resolved from piiat_mitrecar/spindle.yml (the rules), the live maps (piiat_mitrecar.mappings)\n"
           "# and the id recipe (piiat_mitrecar/ids.py) by piiat_mitrecar.spindle — the code the engine\n"
           "# mints with. `python -m piiat_mitrecar.spindle --check` and tests/test_spindle_model.py\n"
           "# fail on drift.\n\n")

_WHAT = {
    REGISTRY_FILE: ("The spindle row-identity registry: per artefact, the CAR object, the identity-key\n"
                    "# version and the ordered identity fields the guid is minted from (name <- source\n"
                    "# path on the event), the scope, the positional fallback; the namespaces and the\n"
                    "# mint rule, materialized."),
    RECORD_FILE: ("The shape of a spindle: what a minted-identity CAR row IS — its header, the two\n"
                  "# native keys it carries, the linkage back to its artefact, and its invariants."),
    GOLDEN_FILE: ("The golden vectors: per entry the key and the guid the engine mints for its golden\n"
                  "# sample at the entry's version, the positional vector and the recipe vector. The\n"
                  "# change protocol's evidence — a guid moves only with its version; the recipe never."),
}

_DOCS = {REGISTRY_FILE: registry_doc, RECORD_FILE: record_doc, GOLDEN_FILE: golden_doc}


def _yaml(doc: dict) -> str:
    return yaml.safe_dump(doc, sort_keys=False, default_flow_style=False,
                          allow_unicode=True, width=100)


def render(filename: str) -> str:
    return _HEADER.format(what=_WHAT[filename]) + _yaml(_DOCS[filename]())


def verify_golden(out_dir: str) -> list[str]:
    """The change protocol over the COMMITTED golden.yml against a fresh
    rendering; [] when every move is legitimate. Per entry (and for the
    positional vector) the guid and the version must move together: a guid
    that moved at the same version is an identity change without a bump; a
    version that moved without its guid cannot be a fresh mint. The recipe
    vector must not move at all — that moves every guid. A missing file, or
    an entry the committed table does not know, is not drift here
    (verify_snapshot reports the file)."""
    path = os.path.join(out_dir, GOLDEN_FILE)
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as fh:
        committed = yaml.safe_load(fh) or {}
    fresh = golden_doc()
    problems: list[str] = []
    if (committed.get("spindle") or {}).get("recipe") != fresh["spindle"]["recipe"]:
        problems.append(f"{GOLDEN_FILE}: the recipe vector moved (canonical_json or a namespace) — "
                        "every guid re-mints: that is a new spindle, not an entry version bump")
    have = {e.get("name"): e for e in committed.get("identities") or [] if isinstance(e, dict)}
    want = {e["name"]: e for e in fresh["identities"]}
    pairs = [("positional", committed.get("positional"), fresh["positional"])]
    pairs += [(n, have[n], want[n]) for n in sorted(set(have) & set(want))]
    for name, old, new in pairs:
        if not isinstance(old, dict):
            continue
        guid_moved, version_moved = old.get("guid") != new["guid"], old.get("version") != new["version"]
        if guid_moved and not version_moved:
            problems.append(f"{name}: golden guid moved at version {new['version']} — the identity (fields, "
                            "names, rendering, recipe or golden sample) changed without a version bump: "
                            "bump `version`, then regenerate")
        elif version_moved and not guid_moved:
            problems.append(f"{name}: version moved {old.get('version')} -> {new['version']} but the golden "
                            "guid did not — _v is hashed, so a bump always re-mints; the committed vector is stale")
    return problems


def write_snapshot(out_dir: str) -> list[str]:
    """Write the snapshot files. Refuses (ValueError) while the committed
    golden table says an identity changed without its version bump — the
    change protocol's gate — so a regenerate can never launder such a change."""
    problems = verify_golden(out_dir)
    if problems:
        raise ValueError("the golden vectors refuse this regenerate:\n  - " + "\n  - ".join(problems))
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for filename in FILES:
        path = os.path.join(out_dir, filename)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(render(filename))
        written.append(path)
    return written


def verify_snapshot(out_dir: str) -> list[str]:
    """The committed snapshot against a fresh rendering; [] when in sync."""
    problems = []
    for filename in FILES:
        path = os.path.join(out_dir, filename)
        if not os.path.exists(path):
            problems.append(f"{path}: missing (run python model/generate.py)")
            continue
        with open(path, encoding="utf-8") as fh:
            if fh.read() != render(filename):
                problems.append(f"{path}: drifted from the registry / maps / engine (run python model/generate.py)")
    return problems


# --------------------------------------------------------------------------- #
# A row against record.yml
# --------------------------------------------------------------------------- #
def _native_of(ev: dict) -> dict:
    nat = ev.get("_native") if "_native" in ev else ev.get("native")
    return nat if isinstance(nat, dict) else {}


def validate_record(ev: dict) -> list[str]:
    """Every way a row fails to be a well-formed spindle; [] means it is one:
    the guid re-mints from its own native.spindle_key, the key names the row's
    object, carries the entry's version and the entry's identity names (or the
    positional fields at the positional version), the scope is in the vocabulary."""
    problems: list[str] = []
    nat = _native_of(ev)
    obj, guid = ev.get("car_object"), ev.get("guid")
    key, scope = nat.get(NATIVE_KEY), nat.get(NATIVE_SCOPE)
    if not isinstance(key, dict) or ids.OBJECT_KEY not in key:
        return [f"native.{NATIVE_KEY}: missing, or not a dict carrying {ids.OBJECT_KEY!r}"]
    if key[ids.OBJECT_KEY] != obj:
        problems.append(f"native.{NATIVE_KEY}.{ids.OBJECT_KEY} {key[ids.OBJECT_KEY]!r} != car_object {obj!r}")
    version = key.get(ids.VERSION_KEY)
    if not isinstance(version, int) or isinstance(version, bool):
        problems.append(f"native.{NATIVE_KEY}.{ids.VERSION_KEY}: missing or not an int (the identity-key version)")
    if any(not isinstance(v, str) for k, v in key.items() if k not in ids.RESERVED_KEYS):
        problems.append(f"native.{NATIVE_KEY}: every value contributes in its string rendering")
    if scope not in ROW_SCOPES:
        problems.append(f"native.{NATIVE_SCOPE} {scope!r} is not one of {list(ROW_SCOPES)}")
    try:
        minted = isinstance(guid, str) and uuid.UUID(guid).version == 5
    except ValueError:
        minted = False
    if not minted:
        problems.append("guid: not a version-5 UUID string")
    elif guid != ids.guid_of(key):
        problems.append(f"guid: does not re-mint from native.{NATIVE_KEY}")
    names = set(key) - set(ids.RESERVED_KEYS)
    if scope == WITHIN_SOURCE:
        if names != set(positional()):
            problems.append(f"a within_source key carries exactly the positional fields {positional()}")
        if version != positional_version():
            problems.append(f"a within_source key carries the positional version {positional_version()}, not {version!r}")
    if scope == CROSS_SOURCE:
        art = str(ev.get("source_artefact"))
        if not any((n == art or n.startswith(art + "/")) and e.get("object") == obj
                   and {f for f, _s, _m in identity_fields(e)} == names and e.get("version") == version
                   for n, e in identities().items()):
            problems.append(f"native.{NATIVE_KEY} names {sorted(names)} at version {version!r} match no "
                            f"registry entry of {art!r} for {obj!r}")
    return problems


# --------------------------------------------------------------------------- #
# CLI — the gen_sources pattern: write, or --check for CI
# --------------------------------------------------------------------------- #
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="piiat_mitrecar.spindle",
                                 description="the spindle identity registry: verify it, snapshot it under model/spindle")
    ap.add_argument("--out", default=DEFAULT_OUT,
                    help="snapshot directory (default: ./model/spindle)")
    ap.add_argument("--check", action="store_true",
                    help="verify registry + committed snapshot against the code; write nothing")
    args = ap.parse_args(argv)
    out_dir = os.path.abspath(args.out)
    problems = verify_registry()
    if problems:
        for p in problems:
            print(f"INVALID: {p}", file=sys.stderr)
        return 1
    problems = verify_golden(out_dir)          # the change protocol: guid and version move together
    if problems:
        for p in problems:
            print(f"INVALID: {p}", file=sys.stderr)
        return 1
    if args.check:
        problems = verify_snapshot(out_dir)
        if problems:
            for p in problems:
                print(f"OUT OF DATE: {p}", file=sys.stderr)
            print("run: python model/generate.py", file=sys.stderr)
            return 1
        print(f"OK: spindle registry ({len(identities())} identities) and {out_dir} in sync")
        return 0
    written = write_snapshot(out_dir)
    print(f"wrote {len(written)} spindle model files to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
